### ISSUE TITLE
Empty (blank) page on launch. Console output on refresh: flatpak-spawn: Invalid byte sequence in conversion input

### ISSUE THREAD

**Issue by travier** [flathub/org.cockpit_project.CockpitClient#33]
This is new instance of https://github.com/flathub/org.cockpit_project.CockpitClient/issues/29 as I can not re-open the issue.

---

Launching Cockpit client gives me an empty (blank) page on launch.

Pressing the refresh button generated the following output in console logs:
```
flatpak-spawn: Invalid byte sequence in conversion input
```

Fedora Kinoite 38, Wayland.
Cockpit Client  org.cockpit_project.CockpitClient       297     stable  system

---

The following does not fix this:
```
$ sudo systemctl reload dbus-broker.service
```

```
$ cat /var/lib/flatpak/exports/share/applications/org.cockpit_project.CockpitClient.desktop
[Desktop Entry]
Type=Application
Name=Cockpit Client
Comment=Connect via ssh to servers running Cockpit
Icon=org.cockpit_project.CockpitClient
Exec=/usr/bin/flatpak run --branch=stable --arch=x86_64 --command=cockpit-client org.cockpit_project.CockpitClient
Categories=Network;RemoteAccess
X-Flatpak=org.cockpit_project.CockpitClient
```

So it looks like https://github.com/cockpit-project/cockpit/pull/19063 wasn't enough.

**Comment by travier** [comment]
I tried running it in a "cleaner" virtual machine and this worked, so I'm not sure where the issue is.

**Comment by travier** [comment]
I've built the latest version from upstream following https://github.com/flathub/org.cockpit_project.CockpitClient/issues/29#issuecomment-1618322755 and it works, so I don't know where the issue is.

**Comment by miha-mohorcic** [comment]
I have similar, but not sure if the same issue on one of my machines (second works OK): 
System: Fedora workstation 38

Starting the cockpit-client via the KDE launcher or "alt+f2" launcher shows the windows with "loading" text shown indefinitely.

Runing the "org.cockpit_project.CockpitClient" from the terminal launches the application and it works correctly. 

What would be the best way to go about logging the difference in behaviour?

**Comment by allisonkarlitskaya** [comment]
I wonder if some old copy of the desktop file was sticking around in your environment...

I feel like this issue is hopefully solved by now?

**Comment by travier** [comment]
I've just tried again and it's not solved for me. Maybe updating this Flatpak will help?

**Comment by travier** [comment]
Current version if 297 when the latest cockpit release is 299.

**Comment by miha-mohorcic** [comment]
I've had same issue for some time (fedora 39). 

Today i did a lot of things, but what i THINK solved it was the:
````
dnf reinstall glibc-common
dnf install glibc-language-source
dnf reinstall glibv-all-langpacks
```

I'm guessing on kinoite there are ways to do this?

Beside some tweaking of the locale settings in KDE, which didn't seem to fix anything. 
Maybe you can narrow it to which one of this (if it does) help.

**Comment by m2Giles** [comment]
Experiencing this as well. I get `AcceleratedSurfaceDMABuf was unable to construct a complete framebuffer` as an error in the terminal.

**Comment by ondrejbudai** [comment]
Same issue on Silverblue (well, the ublue version of it). Can this be ostree-related?

I think that this issues is now more severe because Cockpit Client is one of the recommended replacement for the host switcher, see https://cockpit-project.org/blog/cockpit-322.html. Happy to help debugging, but my knowledge about flatpaks is fairly limited, so I'm not sure where to start.

```console
$ flatpak info org.cockpit_project.CockpitClient 

Cockpit Client - Web-based server interface via ssh

          ID: org.cockpit_project.CockpitClient
         Ref: app/org.cockpit_project.CockpitClient/x86_64/stable
        Arch: x86_64
      Branch: stable
     Version: 322
     License: LGPL-2.1-or-later
      Origin: flathub
  Collection: org.flathub.Stable
Installation: system
   Installed: 12,5 MB
     Runtime: org.gnome.Platform/x86_64/45
         Sdk: org.gnome.Sdk/x86_64/45

      Commit: aa8a09e63bde47edfeaeb77d5c6fae1c2425c29a2471da472c43147207e21dbd
      Parent: 7844846696fce3455460763368da2e0815bfbf7d5524dfbbf0379e5723fbe71a
     Subject: Drop default-branch manifest property (f209d762)
        Date: 2024-08-08 11:00:26 +0000
$ cat /etc/os-release
NAME="Fedora Linux"
VERSION="40.20240823.0 (Silverblue)"
ID=fedora
VERSION_ID=40
VERSION_CODENAME=""
PLATFORM_ID="platform:f40"
PRETTY_NAME="Fedora Linux 40.20240823.0 (Silverblue)"
ANSI_COLOR="0;38;2;60;110;180"
LOGO=fedora-logo-icon
CPE_NAME="cpe:/o:fedoraproject:fedora:40"
DEFAULT_HOSTNAME="fedora"
HOME_URL="https://silverblue.fedoraproject.org"
DOCUMENTATION_URL="https://docs.fedoraproject.org/en-US/fedora-silverblue/"
SUPPORT_URL="https://ask.fedoraproject.org/"
BUG_REPORT_URL="https://github.com/fedora-silverblue/issue-tracker/issues"
REDHAT_BUGZILLA_PRODUCT="Fedora"
REDHAT_BUGZILLA_PRODUCT_VERSION=40
REDHAT_SUPPORT_PRODUCT="Fedora"
REDHAT_SUPPORT_PRODUCT_VERSION=40
SUPPORT_END=2025-05-13
VARIANT="Silverblue"
VARIANT_ID=silverblue
OSTREE_VERSION='40.20240823.0'
```

**Comment by ondrejbudai** [comment]
I investigated a bit, and my issue is that I'm using a mixed locale:

```console
$ locale
LANG=en_US.UTF-8
LC_CTYPE="en_US.UTF-8"
LC_NUMERIC=cs_CZ.UTF-8
LC_TIME=cs_CZ.UTF-8
LC_COLLATE="en_US.UTF-8"
LC_MONETARY=cs_CZ.UTF-8
LC_MESSAGES="en_US.UTF-8"
LC_PAPER=cs_CZ.UTF-8
LC_NAME="en_US.UTF-8"
LC_ADDRESS=cs_CZ.UTF-8
LC_TELEPHONE=cs_CZ.UTF-8
LC_MEASUREMENT=cs_CZ.UTF-8
LC_IDENTIFICATION="en_US.UTF-8"
LC_ALL=
```

Apparently, flatpak fails to installs additional locales in that case, see https://github.com/flatpak/flatpak/issues/5497 and https://github.com/flatpak/flatpak/issues/5564

The workaround is to explicitly tell flatpak to download more locales, kudos to https://github.com/flatpak/flatpak/issues/5497#issuecomment-2016911446. In my case, I had to run:

```console
flatpak config --set languages "en;cs"
flatpak update
```
